In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')
plt.rcParams['figure.figsize'] = (8, 7)
plt.rcParams['font.size'] = 12

In [2]:
df = pd.read_csv('reports_influencers_merge_cleaned.csv')
df.shape

(39, 33)

In [3]:
df.head(3)

Unnamed: 0         IG Handle  click_count  install_count  conversion_rate  \
0           0  fitteacherrachel          345            128         0.371014   
1           1   ardenmcartrette          154             72         0.467532   
2           2       carolrojas7          230             58         0.252174   

   top_perform                    Country    #F/IG       %ER    %13-17  ...  \
0            1  California, United States  24697.0  0.033162  0.026030  ...   
1            1  California, United States  16132.0  0.143380  0.028785  ...   
2            1    New York, United States  13437.0  0.073007  0.022607  ...   

   Top2_Cntr_%       Top3_Cntr  Top3_Cntr_%      Top1_City  Top1_City_%  \
0     0.043866  United Kingdom     0.035316    Los Angeles     0.018216   
1     0.089804          Canada     0.062442    Los Angeles     0.022451   
2     0.332206          Mexico     0.012847  New York City     0.266622   

       Top2_City  Top2_City_%                   Top3_City  Top3_City_%  \
0  New York City     0.015613                     Chicago     0.010781   
1         London     0.020580               New York City     0.015903   
2  Santo Domingo     0.065134  Santiago de los Caballeros     0.052738   

  Credible Followers  
0        19752.66060  
1        14514.44436  
2        10406.95650  

[3 rows x 33 columns]

In [4]:
df_cols = df.columns.to_list()

In [5]:
df_cols

['Unnamed: 0',
 'IG Handle',
 'click_count',
 'install_count',
 'conversion_rate',
 'top_perform',
 'Country',
 '#F/IG',
 '%ER',
 '%13-17',
 '%18-24',
 '%25-34',
 '%35-44',
 '%Male',
 '%Female',
 'Content Vertical/ Interest',
 '%Foll Credibility',
 'Avg likes',
 'Avg comments',
 'Contacts',
 'Top1_Cntr',
 'Top1_Cntr_%',
 'Top2_Cntr',
 'Top2_Cntr_%',
 'Top3_Cntr',
 'Top3_Cntr_%',
 'Top1_City',
 'Top1_City_%',
 'Top2_City',
 'Top2_City_%',
 'Top3_City',
 'Top3_City_%',
 'Credible Followers']

In [6]:
df.describe().T

count          mean           std           min  \
Unnamed: 0           39.0     26.358974     22.727779      0.000000   
click_count          39.0     56.974359     64.134927      2.000000   
install_count        39.0     10.846154     24.787028      0.000000   
conversion_rate      39.0      0.116163      0.139738      0.000000   
top_perform          39.0      0.358974      0.485971      0.000000   
#F/IG                39.0  28627.153846  20085.277494  10204.000000   
%ER                  39.0      0.060524      0.042679      0.010162   
%13-17               39.0      0.049362      0.029804      0.016016   
%18-24               39.0      0.308964      0.108168      0.114131   
%25-34               39.0      0.426281      0.073744      0.188382   
%35-44               39.0      0.162201      0.060989      0.017624   
%Male                39.0      0.189134      0.152726      0.031839   
%Female              39.0      0.810866      0.152726      0.400370   
%Foll Credibility    39.0      0.762950      0.145679      0.339000   
Avg likes            39.0   1449.179487   1449.531247    171.000000   
Avg comments         39.0     65.179487     47.959891      9.000000   
Top1_Cntr_%          39.0      0.644762      0.156258      0.307218   
Top2_Cntr_%          39.0      0.075463      0.060348      0.011990   
Top3_Cntr_%          39.0      0.046516      0.029869      0.005695   
Top1_City_%          39.0      0.072261      0.082205      0.018216   
Top2_City_%          39.0      0.031739      0.019075      0.009393   
Top3_City_%          39.0      0.020354      0.010382      0.006217   
Credible Followers   39.0  21212.892349  14369.489033   4694.811000   

                             25%           50%           75%           max  
Unnamed: 0              9.500000     20.000000     34.500000     84.000000  
click_count            22.000000     42.000000     63.500000    345.000000  
install_count           1.000000      2.000000      6.500000    128.000000  
conversion_rate         0.024892      0.050000      0.142857      0.500000  
top_perform             0.000000      0.000000      1.000000      1.000000  
#F/IG               12825.500000  23200.000000  36162.000000  88086.000000  
%ER                     0.031810      0.050381      0.087858      0.190011  
%13-17                  0.028764      0.040793      0.062820      0.158806  
%18-24                  0.255288      0.299463      0.354998      0.640268  
%25-34                  0.405325      0.429203      0.470019      0.556783  
%35-44                  0.136864      0.158634      0.200161      0.291245  
%Male                   0.096458      0.128579      0.192340      0.599630  
%Female                 0.807659      0.871421      0.903542      0.968161  
%Foll Credibility       0.747250      0.787672      0.851750      0.944499  
Avg likes             665.000000    931.000000   1442.500000   6419.000000  
Avg comments           30.500000     56.000000     89.500000    187.000000  
Top1_Cntr_%             0.514419      0.641053      0.771539      0.936123  
Top2_Cntr_%             0.041312      0.062748      0.083804      0.332206  
Top3_Cntr_%             0.025831      0.044480      0.055461      0.153866  
Top1_City_%             0.027209      0.041551      0.075820      0.415506  
Top2_City_%             0.020584      0.025465      0.036088      0.107948  
Top3_City_%             0.012823      0.017523      0.025714      0.052738  
Credible Followers  10338.538050  16968.105900  25649.518000  65898.355600

In [7]:
# get columns with numeric values
df_num_cols = df.describe().columns
df_num_cols

Index(['Unnamed: 0', 'click_count', 'install_count', 'conversion_rate',
       'top_perform', '#F/IG', '%ER', '%13-17', '%18-24', '%25-34', '%35-44',
       '%Male', '%Female', '%Foll Credibility', 'Avg likes', 'Avg comments',
       'Top1_Cntr_%', 'Top2_Cntr_%', 'Top3_Cntr_%', 'Top1_City_%',
       'Top2_City_%', 'Top3_City_%', 'Credible Followers'],
      dtype='object')

In [8]:
X = df[df_num_cols].drop(columns = ['Unnamed: 0', 'conversion_rate'])
y = df.conversion_rate

In [9]:
X.columns

Index(['click_count', 'install_count', 'top_perform', '#F/IG', '%ER', '%13-17',
       '%18-24', '%25-34', '%35-44', '%Male', '%Female', '%Foll Credibility',
       'Avg likes', 'Avg comments', 'Top1_Cntr_%', 'Top2_Cntr_%',
       'Top3_Cntr_%', 'Top1_City_%', 'Top2_City_%', 'Top3_City_%',
       'Credible Followers'],
      dtype='object')

In [10]:
from sklearn.preprocessing import normalize

In [11]:
X = normalize(X, norm = 'max')

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
rfr = RandomForestRegressor()
rfr.fit(X_train, y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [16]:
y_pred = rfr.predict(X_test)

In [17]:
y_pred

array([0.00593583, 0.00634365, 0.26428847, 0.22761306])

In [18]:
y_test.values

array([0.        , 0.        , 0.34666667, 0.14285714])

In [19]:
sum((y_test.values-y_pred)**2)/len(y_pred) # MSE

0.0035113022048348995

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
import sklearn.metrics

In [22]:
sorted(sklearn.metrics.SCORERS.keys())

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',
 'roc_auc',
 'roc_auc_ovo',
 'roc_auc_ovo_weighted',
 'roc_auc_ovr',
 'roc_auc_ovr_weighted',
 'v_measure_score']

In [23]:
scores = cross_val_score(rfr, X, y, scoring='neg_mean_squared_error', cv=5)
-scores

array([0.05478905, 0.00304837, 0.00942095, 0.02812013, 0.02108776])